/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef VMIDMT_TARGET_HWIO_H
#define VMIDMT_TARGET_HWIO_H

#include <agatti_def.h>

#define HWIO_TCSR_SS_VMIDMT_CLIENT_NON_SEC_INTR_ADDR \
	(AGATTI_TCSR_REGS_BASE + 0x2010)
#define HWIO_TCSR_SS_VMIDMT_CLIENT_NON_SEC_INTR_RMSK 0x3ffff
#define HWIO_TCSR_SS_VMIDMT_CLIENT_NON_SEC_INTR_ENABLE_ADDR \
	(AGATTI_TCSR_REGS_BASE + 0x2050)

#define HWIO_TCSR_SS_VMIDMT_CFG_NON_SEC_INTR_ADDR \
	(AGATTI_TCSR_REGS_BASE + 0x3000)
#define HWIO_TCSR_SS_VMIDMT_CFG_NON_SEC_INTR_RMSK 0x3ffff
#define HWIO_TCSR_SS_VMIDMT_CFG_NON_SEC_INTR_ENABLE_ADDR \
	(AGATTI_TCSR_REGS_BASE + 0x3040)

#define HWIO_TCSR_SS_VMIDMT_CLIENT_SEC_INTR_ADDR \
	(AGATTI_TCSR_REGS_BASE + 0x4010)
#define HWIO_TCSR_SS_VMIDMT_CLIENT_SEC_INTR_RMSK 0x3ffff
#define HWIO_TCSR_SS_VMIDMT_CLIENT_SEC_INTR_ENABLE_ADDR \
	(AGATTI_TCSR_REGS_BASE + 0x4050)

#define HWIO_TCSR_SS_VMIDMT_CFG_SEC_INTR_ADDR \
	(AGATTI_TCSR_REGS_BASE + 0x5000)
#define HWIO_TCSR_SS_VMIDMT_CFG_SEC_INTR_RMSK 0x3ffff
#define HWIO_TCSR_SS_VMIDMT_CFG_SEC_INTR_ENABLE_ADDR \
	(AGATTI_TCSR_REGS_BASE + 0x5040)

#endif /* VMIDMT_TARGET_HWIO_H */
