/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <drivers/qti/pdc/pdc_internal.h>
#include <lib/utils_def.h>

/* PDC GPIO mux mapping for QCS615 (Talos) APSS */
struct pdc_gpio_mapping g_pdc_gpio_mapping[] = {
	/* { trig_config,                  subsystem_irq } */
	/* Mux 0 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 542 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 543 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 544 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 545 },

	/* Mux 4 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 546 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 547 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 548 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 549 },

	/* Mux 8 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 550 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 551 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 552 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 553 },

	/* Mux 12 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 554 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 555 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 556 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 557 },

	/* Mux 16 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 558 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 559 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 560 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 561 },

	/* Mux 20 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 562 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 563 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 564 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 565 },

	/* Mux 24 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 566 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 567 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 568 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 569 },

	/* Mux 28 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 570 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 571 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 572 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 573 },

	/* Mux 32 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 574 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 575 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 576 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 577 },

	/* Mux 36 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 578 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 579 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 580 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 581 },

	/* Mux 40 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 582 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 583 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 584 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 585 },

	/* Mux 44 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 586 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 587 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 588 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 589 },

	/* Mux 48 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 590 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 591 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 592 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 593 },

	/* Mux 52 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 594 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 595 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 596 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 597 },

	/* Mux 56 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 598 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 599 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 600 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 601 },

	/* Mux 60 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 602 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 603 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 604 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 605 },

	/* Mux 64 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 641 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 642 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 643 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 644 },

	/* Mux 68 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 645 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 646 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 647 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 648 },

	/* Mux 72 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 649 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 650 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 651 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 652 },

	/* Mux 76 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 653 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 654 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 655 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 656 },

	/* Mux 80 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 657 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 658 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 659 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 660 },

	/* Mux 84 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 661 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 662 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 663 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 664 },

	/* Mux 88 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 665 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 666 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 667 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 668 },

	/* Mux 92 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 669 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 670 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 671 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 95 },
};

const uint32_t g_pdc_gpio_mapping_size = ARRAY_SIZE(g_pdc_gpio_mapping);
