/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <lib/mmio.h>
#include <lib/utils_def.h>
#include <xpu_target_info.h>

/* XPU_TYPE_COUNT marks reserved positions and xPUs this driver does not name. */
struct xpu_err_pos_to_hal_map xpu_err_pos_to_hal_map
	[ACC_XPU_ERR_INT_REG_NUM][ACC_XPU_ERR_NUM_PER_REG] = {
		{
			{ BIT(0), XPU_TYPE_PMIC_ARB },
			{ BIT(1), XPU_TYPE_COUNT },
			{ BIT(2), XPU_TYPE_BAM_BLSP1_DMA },
			{ BIT(3), XPU_TYPE_COUNT },
			{ BIT(4), XPU_TYPE_COUNT },
			{ BIT(5), XPU_TYPE_MSS_Q6_MPU },
			{ BIT(6), XPU_TYPE_DCC },
			{ BIT(7), XPU_TYPE_IMEM_APU },
			{ BIT(8), XPU_TYPE_COUNT },
			{ BIT(9), XPU_TYPE_SEC_CTRL_APU },
			{ BIT(10), XPU_TYPE_BIMC_MPU0 },
			{ BIT(11), XPU_TYPE_TCSR_REGS },
			{ BIT(12), XPU_TYPE_TCSR_MUTEX },
			{ BIT(13), XPU_TYPE_BOOT_ROM },
			{ BIT(14), XPU_TYPE_RAMBLUR_PIMEM_MPU },
			{ BIT(15), XPU_TYPE_MSS_MPU },
			{ BIT(16), XPU_TYPE_TITAN_SS_APU1 },
			{ BIT(17), XPU_TYPE_CNOC_SNOC_MPU },
			{ BIT(18), XPU_TYPE_CNOC_SNOC_MS_MPU },
			{ BIT(19), XPU_TYPE_QM_MPU_CFG },
			{ BIT(20), XPU_TYPE_CRYPTO0_BAM },
			{ BIT(21), XPU_TYPE_GCC_RPU },
			{ BIT(22), XPU_TYPE_RAMBLUR_PIMEM_APU },
			{ BIT(23), XPU_TYPE_COUNT },
			{ BIT(24), XPU_TYPE_COUNT },
			{ BIT(25), XPU_TYPE_LPASS_SSC_Q6_MPU },
			{ BIT(26), XPU_TYPE_LPASS_VA_MPU },
			{ BIT(27), XPU_TYPE_LPASS_XPU_AUD },
			{ BIT(28), XPU_TYPE_LPASS_RXTX_MPU },
			{ BIT(29), XPU_TYPE_LPASS_XPU_AUD_SB },
			{ BIT(30), XPU_TYPE_COUNT },
			{ BIT(31), XPU_TYPE_COUNT },
		},
		{
			{ BIT(0), XPU_TYPE_IMEM_MPU },
			{ BIT(1), XPU_TYPE_COUNT },
			{ BIT(2), XPU_TYPE_ANOC1_MPU },
			{ BIT(3), XPU_TYPE_MSS_NAV_MPU },
			{ BIT(4), XPU_TYPE_SPDM_APU },
			{ BIT(5), XPU_TYPE_COUNT },
			{ BIT(6), XPU_TYPE_COUNT },
			{ BIT(7), XPU_TYPE_MDSS0 },
			{ BIT(8), XPU_TYPE_HWKM_CFG_KM_APU },
			{ BIT(9), XPU_TYPE_SDC1_SDCC_ICE_KM_APU },
			{ BIT(10), XPU_TYPE_CRYPTO0_CRYPTO_KM_APU },
			{ BIT(11), XPU_TYPE_IPA_0_GSI_TOP },
			{ BIT(12), XPU_TYPE_BOOT_IMEM_SS_MPU },
			{ BIT(13), XPU_TYPE_COUNT },
			{ BIT(14), XPU_TYPE_PKA_APU },
			{ BIT(15), XPU_TYPE_TLMM },
			{ BIT(16), XPU_TYPE_SDC1_SDCC_ICE },
			{ 0, 0 },
		},
	};

const struct xpu_intr_reg_dtls
	xpu_non_sec_intr_status_reg[ACC_XPU_ERR_INT_REG_NUM] = {
		{
			HWIO_TCSR_XPU3_NON_SEC_IRQ_STATUS_REG_0_ADDR,
			HWIO_TCSR_XPU3_NON_SEC_IRQ_STATUS_REG_0_RMSK,
		},
		{
			HWIO_TCSR_XPU3_NON_SEC_IRQ_STATUS_REG_1_ADDR,
			HWIO_TCSR_XPU3_NON_SEC_IRQ_STATUS_REG_1_RMSK,
		},
	};

const struct xpu_intr_reg_dtls
	xpu_sec_intr_status_reg[ACC_XPU_ERR_INT_REG_NUM] = {
		{
			HWIO_TCSR_XPU3_SEC_IRQ_STATUS_REG_0_ADDR,
			HWIO_TCSR_XPU3_SEC_IRQ_STATUS_REG_0_RMSK,
		},
		{
			HWIO_TCSR_XPU3_SEC_IRQ_STATUS_REG_1_ADDR,
			HWIO_TCSR_XPU3_SEC_IRQ_STATUS_REG_1_RMSK,
		},
	};

const struct xpu_intr_reg_dtls
	xpu_non_sec_intr_en_reg[ACC_XPU_ERR_INT_REG_NUM] = {
		{
			HWIO_TCSR_XPU3_NON_SEC_IRQ_ENABLE_0_REG_0_ADDR,
			HWIO_TCSR_XPU3_NON_SEC_IRQ_ENABLE_0_REG_0_RMSK,
		},
		{
			HWIO_TCSR_XPU3_NON_SEC_IRQ_ENABLE_0_REG_1_ADDR,
			HWIO_TCSR_XPU3_NON_SEC_IRQ_ENABLE_0_REG_1_RMSK,
		},
	};

const struct xpu_intr_reg_dtls xpu_sec_intr_en_reg[ACC_XPU_ERR_INT_REG_NUM] = {
	{
		HWIO_TCSR_XPU3_SEC_IRQ_ENABLE_0_REG_0_ADDR,
		HWIO_TCSR_XPU3_SEC_IRQ_ENABLE_0_REG_0_RMSK,
	},
	{
		HWIO_TCSR_XPU3_SEC_IRQ_ENABLE_0_REG_1_ADDR,
		HWIO_TCSR_XPU3_SEC_IRQ_ENABLE_0_REG_1_RMSK,
	},
};

#define XPU_BASE(type, sym) { XPU_TYPE_##type, XPU_ADDR_TYPE(sym), #type }

struct xpu_base_addr_info g_xpu_base_addr_array[] = {
	XPU_BASE(PMIC_ARB, PMIC_ARB_XPU3_GCR0),
	XPU_BASE(BAM_BLSP1_DMA, QUPV3_0_XPU3_GCR0),
	XPU_BASE(MSS_Q6_MPU, MDSP_MPU_CFG_XPU3_GCR0),
	XPU_BASE(DCC, DCC_XPU3_GCR0),
	XPU_BASE(IMEM_APU, OCIMEM_APU_XPU3_GCR0),
	XPU_BASE(SEC_CTRL_APU, SEC_CTRL_APU_XPU3_GCR0),
	XPU_BASE(BIMC_MPU0, BIMC_S_DDR0_XPU3_GCR0),
	XPU_BASE(TCSR_REGS, TCSR_REGS_XPU3_GCR0),
	XPU_BASE(TCSR_MUTEX, TCSR_MUTEX_XPU3_GCR0),
	XPU_BASE(BOOT_ROM, BOOT_ROM_XPU3_GCR0),
	XPU_BASE(RAMBLUR_PIMEM_MPU, RAMBLUR_PIMEM_MPU_XPU3_GCR0),
	XPU_BASE(MSS_MPU, MSS_XPU3_GCR0),
	XPU_BASE(TITAN_SS_APU1, CAMSS_A_XPU3_XPU3_GCR0),
	XPU_BASE(CNOC_SNOC_MPU, CNOC_MS_MPU_XPU3_GCR0),
	XPU_BASE(CNOC_SNOC_MS_MPU, CNOC_SNOC_MS_MPU_XPU3_GCR0),
	XPU_BASE(QM_MPU_CFG, QM_MPU_CFG_QM_MPU_CFG_XPU3_GCR0),
	XPU_BASE(CRYPTO0_BAM, CRYPTO0_CRYPTO_BAM_XPU3_GCR0),
	XPU_BASE(GCC_RPU, GCC_RPU_XPU3_GCR0),
	XPU_BASE(RAMBLUR_PIMEM_APU, RAMBLUR_PIMEM_APU_XPU3_GCR0),
	XPU_BASE(LPASS_SSC_Q6_MPU, LPASS_Q6_MPU_XPU3_GCR0),
	XPU_BASE(LPASS_VA_MPU, LPASS_VA_XPU3_GCR0),
	XPU_BASE(LPASS_XPU_AUD, LPASS_AUD_XPU3_GCR0),
	XPU_BASE(LPASS_RXTX_MPU, LPASS_RXTX_XPU3_GCR0),
	XPU_BASE(LPASS_XPU_AUD_SB, LPASS_AUD_SB_XPU3_GCR0),
	XPU_BASE(IMEM_MPU, OCIMEM_MPU_XPU3_GCR0),
	XPU_BASE(ANOC1_MPU, SNOC_AGGRE_MS_MPU_XPU3_GCR0),
	XPU_BASE(MSS_NAV_MPU, SNOC_MSS_NAV_MS_MPU_XPU3_GCR0),
	XPU_BASE(SPDM_APU, QDSS_QDSS_SPDM_SPDM_XPU3_GCR0),
	XPU_BASE(MDSS0, MDSS_XPU_XPU3_GCR0),
	XPU_BASE(HWKM_CFG_KM_APU, HWKM_MASTER_CFG_KM_XPU3_GCR0),
	XPU_BASE(SDC1_SDCC_ICE_KM_APU, PERIPH_SS_SDC1_SDCC_ICE_KM_XPU3_GCR0),
	XPU_BASE(CRYPTO0_CRYPTO_KM_APU, CRYPTO0_CRYPTO_KM_XPU3_GCR0),
	XPU_BASE(IPA_0_GSI_TOP, IPA_0_GSI_TOP_XPU3_GCR0),
	XPU_BASE(BOOT_IMEM_SS_MPU, SNOC_BOOTIMEM_MS_MPU_XPU3_GCR0),
	XPU_BASE(PKA_APU, PKA_WRAPPER_XPU3_GCR0),
	XPU_BASE(TLMM, TLMM_XPU_XPU3_GCR0),
	XPU_BASE(SDC1_SDCC_ICE, PERIPH_SS_SDC1_SDCC_ICE_XPU3_GCR0),
};

uint32_t g_xpu_base_addr_array_count = ARRAY_SIZE(g_xpu_base_addr_array);

void xpu_configure_tz(void)
{
}
